# Generated by Django 4.0.4 on 2022-06-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('prize', models.CharField(max_length=200)),
                ('emi', models.CharField(max_length=200)),
            ],
        ),
    ]
