# Generated by Django 4.0.4 on 2022-06-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
